/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import universidadejemplo.AccesoADatos.*;
import universidadejemplo.Entidades.Materia;

/**
 *
 * @author Editor
 */
public class FormularioMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioMateria
     */
    public FormularioMateria() {
        initComponents();
        setTitle("Materias");
        jBGuardar.setEnabled(false);
        jBEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jTCodigo = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTAño = new javax.swing.JTextField();
        jRBEstado = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(438, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel4.setText("Año:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 30, 30));

        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 20));

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 219, -1, -1));

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 398, -1, -1));

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 398, -1, -1));

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 398, -1, -1));

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 398, -1, -1));

        jTCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(jTCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 210, 108, 30));

        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 251, 108, 30));

        jTAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTAñoKeyTyped(evt);
            }
        });
        getContentPane().add(jTAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 296, 108, 30));
        getContentPane().add(jRBEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("   MATERIAS");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadejemplo/Recursos/alumnos.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadejemplo/Recursos/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 0, -1, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        jBGuardar.setEnabled(false);
        if (jTCodigo.isEnabled()) {
            MateriaData mt = new MateriaData();
            try {
                int cod = Integer.parseInt(jTCodigo.getText());
                Materia mat = mt.buscarMateria(cod);
                jTAño.setText(mat.getAño() + "");
                jTNombre.setText(mat.getNombre());
                jRBEstado.setSelected(true);
                jBEliminar.setEnabled(true);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el NUMERO de identificacion de la materia");
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(this, "No existe la materia");
            }
        } else {
            jTCodigo.setEnabled(true);
            jTAño.setText("");
            jTNombre.setText("");
            jRBEstado.setSelected(false);
        }
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        jBGuardar.setEnabled(true);
        jBEliminar.setEnabled(false);
        jTAño.setText("");
        jTNombre.setText("");
        jRBEstado.setSelected(false);
        jTCodigo.setText("");
        jTCodigo.setEnabled(false);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        MateriaData mt = new MateriaData();

        try {
            int idMateria = Integer.parseInt(jTCodigo.getText());
            mt.eliminarMateria(idMateria);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el NUMERO de identificacion de la materia");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "No existe la materia");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        MateriaData a1 = new MateriaData();
        Materia al1 = new Materia();
        
     
        try {
            if (jTAño.getText().length() == 4 && Integer.parseInt(jTAño.getText()) <= (LocalDate.now().getYear())) {
                if (!jTNombre.getText().isEmpty()&& jRBEstado.isSelected()
                        && !jTAño.getText().isEmpty()) {
                    al1.setNombre(jTNombre.getText().toLowerCase());
                    al1.setAño(Integer.parseInt(jTAño.getText()));
                    al1.setEstado(true);
                    a1.guardarMateria(al1);
                } else {
                    JOptionPane.showMessageDialog(this, "Tenes que completar todos los campos");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Verifique la fecha ingresada, ej: 2000");
                jTAño.setText("");
                jTNombre.setText("");
                jRBEstado.setSelected(false);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Solo tenes que ingresar numeros");
        }

    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodigoKeyTyped
        int tecla = evt.getKeyChar();
       boolean numeros = tecla >= 48&& tecla <=57;
        if (!(numeros)) {
            evt.consume();
        }
        if ((jTCodigo.getText().length()>=4)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTCodigoKeyTyped

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
          int tecla = evt.getKeyChar();
         boolean may= tecla >=65 && tecla <=90;
         boolean min= tecla >= 97 && tecla <=122;
         boolean esp= tecla == 32;
         if (!(may||min||esp)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAñoKeyTyped
          int tecla = evt.getKeyChar();
       boolean numeros = tecla >= 48&& tecla <=57;
        if (!(numeros)) {
            evt.consume();
        }
         if ((jTAño.getText().length()>=4)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTAñoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JTextField jTAño;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
