/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

/**
 *
 * @author Editor
 */
public class Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jAlumno = new javax.swing.JMenu();
        jFormularioAlumno = new javax.swing.JMenuItem();
        jMateria = new javax.swing.JMenu();
        jFormularioMateria = new javax.swing.JMenuItem();
        jAdministracion = new javax.swing.JMenu();
        jManejoInscripciones = new javax.swing.JMenuItem();
        jManipulacionNotas = new javax.swing.JMenuItem();
        jConsultas = new javax.swing.JMenu();
        jAlumnosPorMateria = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();

        jAlumno.setText("Alumno");

        jFormularioAlumno.setText("Formulario de  Alumno");
        jAlumno.add(jFormularioAlumno);

        jMenuBar1.add(jAlumno);

        jMateria.setText("Materia");

        jFormularioMateria.setText("Formulario de Materia");
        jMateria.add(jFormularioMateria);

        jMenuBar1.add(jMateria);

        jAdministracion.setText("Administracion");

        jManejoInscripciones.setText("Manejo de Inscripciones");
        jAdministracion.add(jManejoInscripciones);

        jManipulacionNotas.setText("Manipulacion de notas");
        jAdministracion.add(jManipulacionNotas);

        jMenuBar1.add(jAdministracion);

        jConsultas.setText("Consultas");

        jAlumnosPorMateria.setText("Alumnos por Materia");
        jConsultas.add(jAlumnosPorMateria);

        jMenuBar1.add(jConsultas);

        jSalir.setText("Salir");
        jMenuBar1.add(jSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAdministracion;
    private javax.swing.JMenu jAlumno;
    private javax.swing.JMenuItem jAlumnosPorMateria;
    private javax.swing.JMenu jConsultas;
    private javax.swing.JMenuItem jFormularioAlumno;
    private javax.swing.JMenuItem jFormularioMateria;
    private javax.swing.JMenuItem jManejoInscripciones;
    private javax.swing.JMenuItem jManipulacionNotas;
    private javax.swing.JMenu jMateria;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jSalir;
    // End of variables declaration//GEN-END:variables
}
